### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by CleverSource** [suufi/Sphere#1]
How do you setup the server thing? port:9000 on a website?

**Comment by suufi** [comment]
I forgot to push out the updated README.md but it's just a matter of putting the API on a VPS and doing `npm install` so it can install the dependencies. Run `node ModSystem.js` to make sure you have no errors. When you're done, you can use a process manager like pm2 or nodemon to keep the API online even after you close the Terminal. If you're using PM2, you would do something like `pm2 start ModSystem.js`.

**Comment by suufi** [comment]
The README.md has been updated to address this.
